with open('app.py', 'r', encoding='utf-8') as f:
    content = f.read()

fixes = [
    # 1. Conflict 500: giữ CSS của bạn 3 (HEAD) - type-filters, interest-filters, section-title
    (
        "<<<<<<< HEAD\ninput:focus, select:focus { border-color: var(--accent); box-shadow: 0 0 0 2px var(--accent-glow); }\n\n#type-filters { display: flex; flex-wrap: wrap; gap: 8px; margin: 12px 0 16px; }\n#interest-filters { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 16px; }\n.section-title { font-size: 12px; font-weight: 600; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.6px; margin-top: 8px; margin-bottom: 8px; }\n=======\n.toggle-form-btn:hover {\n  background: var(--accent);\n  color: #0a0c12;\n}\n/* Form section \u2013 collapsible */\n#form-section {\n  background: rgba(20,24,34,0.6);\n  border-bottom: 1px solid var(--border);\n  transition: max-height 0.4s ease, padding 0.3s;\n  overflow-y: auto;\n  padding: 0 20px;\n}\n#form-section.collapsed {\n  max-height: 0 !important;\n  padding: 0 20px !important;\n  border-bottom: none;\n}\n#form-inner {\n  padding: 20px 0;\n}\n/* 4 input tr\u00ean 1 h\u00e0ng */\n.form-row-compact {\n  display: flex;\n  gap: 12px;\n  margin-bottom: 16px;\n}\n.form-group {\n  flex: 1;\n}\n>>>>>>> origin/main",
        "input:focus, select:focus { border-color: var(--accent); box-shadow: 0 0 0 2px var(--accent-glow); }\n\n#type-filters { display: flex; flex-wrap: wrap; gap: 8px; margin: 12px 0 16px; }\n#interest-filters { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 16px; }\n.section-title { font-size: 12px; font-weight: 600; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.6px; margin-top: 8px; margin-bottom: 8px; }\n.toggle-form-btn:hover {\n  background: var(--accent);\n  color: #0a0c12;\n}\n/* Form section \u2013 collapsible */\n#form-section {\n  background: rgba(20,24,34,0.6);\n  border-bottom: 1px solid var(--border);\n  transition: max-height 0.4s ease, padding 0.3s;\n  overflow-y: auto;\n  padding: 0 20px;\n}\n#form-section.collapsed {\n  max-height: 0 !important;\n  padding: 0 20px !important;\n  border-bottom: none;\n}\n#form-inner {\n  padding: 20px 0;\n}\n/* 4 input tr\u00ean 1 h\u00e0ng */\n.form-row-compact {\n  display: flex;\n  gap: 12px;\n  margin-bottom: 16px;\n}\n.form-group {\n  flex: 1;\n}"
    ),

    # 2. Conflict 761: giữ CSS đầy đủ của bạn 3 (HEAD) - stop-body, map-popup, badges
    (
        "<<<<<<< HEAD\n.stop-body { flex: 1; min-width: 0; }\n.stop-name { font-size: 14px; font-weight: 500; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }\n.stop-meta { font-size: 11px; color: var(--text-muted); margin-top: 4px; display: flex; flex-wrap: wrap; gap: 10px; }\n  .map-popup {\n    background: rgba(20,20,25,0.92);\n    color: white;\n    border-radius: 14px;\n    padding: 10px;\n    backdrop-filter: blur(12px);\n    border: 1px solid rgba(255,255,255,0.08);\n    box-shadow: 0 8px 30px rgba(0,0,0,0.45);\n  }\n\n  .map-popup b {\n    font-size: 15px;\n    color: #f0d79a;\n  }\n\n  .map-popup .meta {\n    opacity: 0.75;\n    margin: 4px 0;\n    font-size: 12px;\n  }\n.stop-time { color: var(--accent); font-weight: 500; }\n.badge-infeasible { background: rgba(255,94,94,0.15); color: #ff5e5e; padding: 2px 8px; border-radius: 20px; font-size: 10px; }\n.badge-anchor { background: rgba(212,184,122,0.15); color: var(--accent); padding: 2px 8px; border-radius: 20px; font-size: 10px; }\n\n=======\n.stop-name { font-size: 13px; font-weight: 500; }\n.stop-meta { font-size: 10px; color: var(--text-muted); display: flex; flex-wrap: wrap; gap: 8px; margin-top: 2px; }\n>>>>>>> origin/main",
        ".stop-body { flex: 1; min-width: 0; }\n.stop-name { font-size: 14px; font-weight: 500; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }\n.stop-meta { font-size: 11px; color: var(--text-muted); margin-top: 4px; display: flex; flex-wrap: wrap; gap: 10px; }\n  .map-popup {\n    background: rgba(20,20,25,0.92);\n    color: white;\n    border-radius: 14px;\n    padding: 10px;\n    backdrop-filter: blur(12px);\n    border: 1px solid rgba(255,255,255,0.08);\n    box-shadow: 0 8px 30px rgba(0,0,0,0.45);\n  }\n\n  .map-popup b {\n    font-size: 15px;\n    color: #f0d79a;\n  }\n\n  .map-popup .meta {\n    opacity: 0.75;\n    margin: 4px 0;\n    font-size: 12px;\n  }\n.stop-time { color: var(--accent); font-weight: 500; }\n.badge-infeasible { background: rgba(255,94,94,0.15); color: #ff5e5e; padding: 2px 8px; border-radius: 20px; font-size: 10px; }\n.badge-anchor { background: rgba(212,184,122,0.15); color: var(--accent); padding: 2px 8px; border-radius: 20px; font-size: 10px; }\n"
    ),

    # 3. Conflict 859: giữ HTML form của bạn 3 (HEAD) - form-row, type-filters, interest-filters, anchor
    (
        "<<<<<<< HEAD\n    <div class=\"form-row\">\n      <div class=\"form-group\"><label>B\u1eaft \u0111\u1ea7u l\u00fac</label><select id=\"start_hour\"><option value=\"6\">06:00</option><option value=\"7\" selected>07:00</option><option value=\"8\">08:00</option><option value=\"9\">09:00</option></select></div>\n      <div class=\"form-group\"><label>K\u1ebft th\u00fac l\u00fac</label><select id=\"end_hour\"><option value=\"19\">19:00</option><option value=\"20\">20:00</option><option value=\"21\" selected>21:00</option><option value=\"22\">22:00</option></select></div>\n    </div>\n    <label>Lo\u1ea1i \u0111\u1ecba \u0111i\u1ec3m</label>\n    <div id=\"type-filters\"><div class=\"type-pill active\" data-type=\"all\">\u2728 T\u1ea5t c\u1ea3</div></div>\n    <div class=\"section-title\">Phong c\u00e1ch du l\u1ecbch</div>\n    <div id=\"interest-filters\">\n      <div class=\"type-pill\">\U0001f33f Chill</div>\n      <div class=\"type-pill\">\U0001f4f8 S\u1ed1ng \u1ea3o</div>\n      <div class=\"type-pill\">\U0001f304 S\u0103n m\u00e2y</div>\n      <div class=\"type-pill\">\U0001f319 View \u0111\u00eam</div>\n    </div>\n    <label>\U0001f4cc \u0110i\u1ec3m b\u1eaft bu\u1ed9c</label>\n    <div id=\"anchor-section\">\n      <div style=\"position:relative;\"><input type=\"text\" id=\"anchor-input\" placeholder=\"T\u00ecm \u0111\u1ecba \u0111i\u1ec3m...\" autocomplete=\"off\"><div id=\"anchor-drop\" style=\"display:none; position:absolute; top:100%; left:0; right:0; background:var(--surface); border:1px solid var(--border); border-radius:12px; max-height:200px; overflow-y:auto; z-index:100; margin-top:4px;\"></div></div>\n      <div id=\"anchor-tags\" style=\"display:flex; flex-wrap:wrap; gap:6px; margin-top:8px;\"></div>\n    </div>\n    <button id=\"btn-optimize\" onclick=\"optimize()\">\U0001f5fa T\u1ed1i \u01b0u l\u1ed9 tr\u00ecnh</button>\n=======\n>>>>>>> origin/main",
        "    <div class=\"form-row\">\n      <div class=\"form-group\"><label>B\u1eaft \u0111\u1ea7u l\u00fac</label><select id=\"start_hour\"><option value=\"6\">06:00</option><option value=\"7\" selected>07:00</option><option value=\"8\">08:00</option><option value=\"9\">09:00</option></select></div>\n      <div class=\"form-group\"><label>K\u1ebft th\u00fac l\u00fac</label><select id=\"end_hour\"><option value=\"19\">19:00</option><option value=\"20\">20:00</option><option value=\"21\" selected>21:00</option><option value=\"22\">22:00</option></select></div>\n    </div>\n    <label>Lo\u1ea1i \u0111\u1ecba \u0111i\u1ec3m</label>\n    <div id=\"type-filters\"><div class=\"type-pill active\" data-type=\"all\">\u2728 T\u1ea5t c\u1ea3</div></div>\n    <div class=\"section-title\">Phong c\u00e1ch du l\u1ecbch</div>\n    <div id=\"interest-filters\">\n      <div class=\"type-pill\">\U0001f33f Chill</div>\n      <div class=\"type-pill\">\U0001f4f8 S\u1ed1ng \u1ea3o</div>\n      <div class=\"type-pill\">\U0001f304 S\u0103n m\u00e2y</div>\n      <div class=\"type-pill\">\U0001f319 View \u0111\u00eam</div>\n    </div>\n    <label>\U0001f4cc \u0110i\u1ec3m b\u1eaft bu\u1ed9c</label>\n    <div id=\"anchor-section\">\n      <div style=\"position:relative;\"><input type=\"text\" id=\"anchor-input\" placeholder=\"T\u00ecm \u0111\u1ecba \u0111i\u1ec3m...\" autocomplete=\"off\"><div id=\"anchor-drop\" style=\"display:none; position:absolute; top:100%; left:0; right:0; background:var(--surface); border:1px solid var(--border); border-radius:12px; max-height:200px; overflow-y:auto; z-index:100; margin-top:4px;\"></div></div>\n      <div id=\"anchor-tags\" style=\"display:flex; flex-wrap:wrap; gap:6px; margin-top:8px;\"></div>\n    </div>\n    <button id=\"btn-optimize\" onclick=\"optimize()\">\U0001f5fa T\u1ed1i \u01b0u l\u1ed9 tr\u00ecnh</button>"
    ),

    # 4. Conflict 1117: giữ icon đẹp hơn của bạn 3 (HEAD) - divIcon lớn hơn có box-shadow
    (
        "<<<<<<< HEAD\n      const icon = L.divIcon({\n  html: `<div style=\"\n    background:${day.color};\n    color:white;\n    border-radius:50%;\n    width:34px;\n    height:34px;\n    display:flex;\n    align-items:center;\n    justify-content:center;\n    font-weight:700;\n    font-size:12px;\n    border:3px solid rgba(255,255,255,0.9);\n    box-shadow:0 0 20px ${day.color};\n    opacity:${stop.feasible?1:0.45};\n  \">${stop.idx}</div>`,\n  iconSize:[34,34],\n  iconAnchor:[17,17]\n});\n=======\n      const icon = L.divIcon({ className: '', html: `<div style=\"background:${day.color};color:white;border-radius:50%;width:28px;height:28px;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:11px;border:2px solid white;box-shadow:0 2px 6px rgba(0,0,0,0.5);opacity:${stop.feasible?1:0.4};\">${stop.idx}</div>`, iconSize:[28,28], iconAnchor:[14,14] });\n>>>>>>> origin/main",
        "      const icon = L.divIcon({\n  html: `<div style=\"\n    background:${day.color};\n    color:white;\n    border-radius:50%;\n    width:34px;\n    height:34px;\n    display:flex;\n    align-items:center;\n    justify-content:center;\n    font-weight:700;\n    font-size:12px;\n    border:3px solid rgba(255,255,255,0.9);\n    box-shadow:0 0 20px ${day.color};\n    opacity:${stop.feasible?1:0.45};\n  \">${stop.idx}</div>`,\n  iconSize:[34,34],\n  iconAnchor:[17,17]\n});"
    ),
]

count = 0
for old, new in fixes:
    if old in content:
        content = content.replace(old, new)
        count += 1
        print(f'Fixed {count}!')
    else:
        print(f'NOT FOUND (fix {count+1})')

with open('app.py', 'w', encoding='utf-8') as f:
    f.write(content)

print(f'\nDone! Fixed {count}/4 conflicts')
